on:
  push:
    branches: [ axe-fix ]

env:
  # Url for the running web app
  APP: http://localhost:1338
  # Url to test
  URL: http://localhost:1338

jobs:
  axe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webpage: [perceivable] #, operable, understandable
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Chrome browser-action
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: 123
      - name: Chrome check
        run: |
          chrome --version
          echo "Chrome path: ${{ steps.setup-chrome.outputs.chrome-path }}"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on $APP
      - name: Run axe-core
        run: |
          npm install -g @axe-core/cli
          axe --chromedriver-path ${{ steps.setup-chrome.outputs.chrome-path }} $APP/${{ matrix.webpage }} --dir ./results/axe/ --save axe-results-${{ matrix.webpage }}.json
      - name: Archive axe-core test results
        uses: actions/upload-artifact@v4
        with:
          name: Axe-core
          path: results/axe/axe-results.json
