name: Web Accessibility Testing Tools Results
# This workflow runs all tools on a given webpage and save the results as github artifacts.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Chrome browser-action
        uses: browser-actions/setup-chrome@v1
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:1338
      - name: Run axe-core
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:1338 --dir ./results/axe/ --save axe-results.json
      - name: Archive axe-core test results
        uses: actions/upload-artifact@v4
        with:
          name: Axe-core
          path: results/axe/axe-results.json

  achecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:1338
      - name: Run accessibility-checker
        run: |
          npm install accessibility-checker
          npx achecker "http://localhost:1338/understandable"
      - name: Archive accessibility-checker test results
        uses: actions/upload-artifact@v4
        with:
          name: Accessibility-checker
          path: results/achecker/*

  htmlcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:1338
      - name: Run HTML_CodeSniffer
        run: |
          npm i --save html_codesniffer
          cd node_modules/html_codesniffer
          npm install
          cd ../..
          npm i puppeteer
          bash test.bash run htmlcs "http://localhost:1338/"
      - name: Archive HTML_CodeSniffer test results
        uses: actions/upload-artifact@v4
        with:
          name: HTML_CodeSniffer
          path: results/HTML_CodeSniffer/*
